packages:
  - apps/*
  - libs/*
overrides:
  # Security patches - consolidated and updated
  next@<15.2.2: '>=15.2.2'
  koa@<2.16.1: '>=2.16.1'
  esbuild@<=0.24.2: '>=0.25.0'
  cross-spawn@<6.0.6: '>=6.0.6'
  nanoid@<3.3.8: '>=3.3.8'
