# @file        .github/workflows/redis-password-rotation.yml
# @description Automated Redis password rotation for security compliance
# @author      SalamBot Team (contact: info@salambot.ma)
# @created     2025-01-20
# @updated     2025-01-20
# @project     SalamBot - AI CRM for Moroccan SMEs

name: Redis Password Rotation

# Exécution planifiée le 1er de chaque mois à 02:00 UTC
# et possibilité de déclenchement manuel
on:
  schedule:
    # Cron: minute hour day month day-of-week
    # 0 2 1 * * = 02:00 UTC le 1er de chaque mois
    - cron: '0 2 1 * *'

  # Permet le déclenchement manuel depuis l'interface GitHub
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rotate password for'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production
      dry_run:
        description: 'Dry run mode (simulation only)'
        required: false
        default: false
        type: boolean

# Variables d'environnement globales
env:
  NODE_VERSION: '22'
  TERRAFORM_VERSION: '1.6.0'

jobs:
  rotate-redis-password:
    name: Rotate Redis Password
    runs-on: ubuntu-latest

    # Permissions nécessaires
    permissions:
      contents: read
      id-token: write # Pour l'authentification Google Cloud

    # Matrice pour les environnements (si déclenchement automatique)
    strategy:
      matrix:
        environment: ${{ github.event_name == 'workflow_dispatch' && fromJson(format('["'{0}'"]', github.event.inputs.environment)) || fromJson('["dev", "production"]') }}

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Dependencies
        run: |
          npm ci
          npm run build:config

      - name: Verify Environment Configuration
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Dry Run: ${{ github.event.inputs.dry_run || 'false' }}"

          # Vérifier que Terraform est configuré
          cd infra/terraform
          terraform version
          terraform init -backend=false
          terraform validate

      - name: Initialize Terraform Backend
        working-directory: infra/terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="prefix=redis/${{ matrix.environment }}"

      - name: Check Current Redis Configuration
        run: |
          echo "🔍 Vérification de la configuration Redis actuelle..."

          # Utiliser le script de validation pour vérifier l'état
          node -e "
            const { checkRedisHealth } = require('./libs/config/dist/redis');
            checkRedisHealth().then(health => {
              console.log('État Redis:', health);
              if (health.status !== 'healthy') {
                console.warn('⚠️ Redis n\'est pas en état healthy');
              }
            }).catch(err => {
              console.warn('⚠️ Impossible de vérifier Redis:', err.message);
            });
          "
        env:
          NODE_ENV: ${{ matrix.environment }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Dry Run - Simulate Password Rotation
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "🧪 Mode simulation - Rotation du mot de passe Redis"
          echo "Environment: ${{ matrix.environment }}"
          echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

          # Simulation des étapes principales
          echo "✓ Génération d'un nouveau mot de passe (simulé)"
          echo "✓ Mise à jour Secret Manager (simulé)"
          echo "✓ Mise à jour Firestore (simulé)"
          echo "✓ Application Terraform (simulé)"
          echo "✓ Vérification connexion Redis (simulé)"

          echo "🎉 Simulation terminée avec succès!"

      - name: Execute Password Rotation
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "🔄 Exécution de la rotation du mot de passe Redis..."

          # Exécuter le script de rotation
          npx tsx scripts/rotate-redis-password.ts
        env:
          NODE_ENV: ${{ matrix.environment }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        timeout-minutes: 15

      - name: Verify Redis Health After Rotation
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "🏥 Vérification de la santé Redis après rotation..."

          # Attendre un peu pour que les changements se propagent
          sleep 10

          # Vérifier la santé Redis
          node -e "
            const { checkRedisHealth } = require('./libs/config/dist/redis');
            
            async function verify() {
              let attempts = 0;
              const maxAttempts = 5;
              
              while (attempts < maxAttempts) {
                try {
                  const health = await checkRedisHealth();
                  console.log('Tentative', attempts + 1, '- État Redis:', health);
                  
                  if (health.status === 'healthy') {
                    console.log('✅ Redis est en bonne santé!');
                    process.exit(0);
                  }
                  
                  attempts++;
                  if (attempts < maxAttempts) {
                    console.log('⏳ Attente avant nouvelle tentative...');
                    await new Promise(resolve => setTimeout(resolve, 5000));
                  }
                } catch (error) {
                  console.error('Erreur lors de la vérification:', error.message);
                  attempts++;
                }
              }
              
              console.error('❌ Redis n\'est pas accessible après rotation');
              process.exit(1);
            }
            
            verify();
          "
        env:
          NODE_ENV: ${{ matrix.environment }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        timeout-minutes: 5

      - name: Cleanup Terraform Plans
        if: always()
        working-directory: infra/terraform
        run: |
          # Nettoyer les fichiers de plan temporaires
          rm -f tfplan *.tfplan

      - name: Report Results
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Rotation du mot de passe Redis réussie pour l'environnement ${{ matrix.environment }}"
          else
            echo "❌ Échec de la rotation du mot de passe Redis pour l'environnement ${{ matrix.environment }}"
          fi

          echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "Environment: ${{ matrix.environment }}"
          echo "Dry Run: ${{ github.event.inputs.dry_run || 'false' }}"

      # TODO: Ajouter une notification Slack/Teams en cas d'échec
      - name: Notify on Failure
        if: failure()
        run: |
          echo "🚨 ALERTE: Échec de la rotation du mot de passe Redis!"
          echo "Environment: ${{ matrix.environment }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

          # TODO: Intégrer avec un service de notification
          # curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          #   -H 'Content-type: application/json' \
          #   --data '{"text":"🚨 Échec rotation Redis password pour ${{ matrix.environment }}"}'
