name: Trae-Bot CI

on:
  push:
    branches:
      - feature/trae-bot-setup
    paths:
      - 'tools/trae-bot.ts'
      - '.github/workflows/trae.yml'
  pull_request:
    branches: [main]
    paths:
      - 'tools/**'
      - '.github/workflows/trae.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm nx lint
      - name: Tests
        run: pnpm nx test
