# @file        .github/workflows/trae.yml
# @description Trae Bot CI workflow for automated development assistance
# @author      SalamBot Team (contact: info@salambot.ma)
# @created     2025-01-20
# @updated     2025-01-20
# @project     SalamBot - AI CRM for Moroccan SMEs

name: Trae Bot CI

on:
  push:
    branches:
      - feature/trae-bot-setup
    paths:
      - 'tools/trae-bot.ts'
      - '.github/workflows/trae.yml'
  pull_request:
    branches: [main]
    paths:
      - 'tools/**'
      - '.github/workflows/trae.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Tests
        run: pnpm test
